### ISSUE TITLE
NoItem 2.0.7-SNAPSHOT-193 not blocking Project Table crafting

### ISSUE THREAD

**Issue by nvx** [World-of-Tomorrow/NoItem#40]
Running Tekkit, blocking crafting of DM Blocks (126:8). Using the regular 2x2 crafting area in your inventory it successfully blocks crafting, thus confirming permissions are working.

Using PermissionsBukkit 2.0 with the node noitem.nocraft.126.8 set to true. Output of "permissions check noitem.nocraft.126.8 NVX" follows

2012-10-02 04:18:25 [INFO] Player NVX sets noitem.nocraft.126.8 to true.

Crafting a DM block in a project table however, works fine without issues, when it should be blocked.

Project Table is from RP2 PR5b2 and has id 137:3

I am using the default CustomBlocks.yml which appears to have the correct details in it for the Project Table.

debug_dump.txt: http://pastie.org/4892521

CustomBlocks.yml

``` yml
RMFurnace:
    id: 126
    data: 4
    type: furnace
    itemSlots: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    fuelSlots: [0]
    resultSlots: [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
    usesFuel: true

BlulectricFurnace:
    id: 137
    data: 4
    type: furnace
    itemSlots: [0, 1, 2, 3, 4, 5, 6, 7 , 8]
    resultSlots: [10]

ProjectTable:
    id: 137
    data: 3
    type: workbench
    resultSlots: [9]
    recipeSlots: [0, 1, 2, 3, 4, 5, 6, 7, 8]

AutomaticCraftingTableMkII:
    id: 194
    data: 1
    type: workbench
    recipeSlots: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    resultSlots: [0]
    fakeRecipeItems: true
```

The issue also occurs with 2.0.6 (which is what prompted me to try 2.0.7)

Edit: Completely unrelated, but eh - You should list your downloads on BukkitDev as being compatible with 1.2.5 as well as 1.3.x so Tekkit users don't hesitate to upgrade to newer versions. I know I wasn't too sure if upgrading would just result in a bunch of NPEs causing me to hesitate before trying anything newer than 2.0.5. :) The "nohold" function works great though. :)
