### ISSUE TITLE
Nodes Not Effective in Tekkit 3.1.2

### ISSUE THREAD

**Issue by bjeardoe** [World-of-Tomorrow/NoItem#43]
Using Noitem 1.0.6

Following are permissions nodes I'm using for this guys group, I'm using PeX

```
- noitem.nopickup.126.11
- noitem.nodrop.126.11
- noitem.noplace.126.11
- noitem.nohold.126.11
- noitem.nowear.126.11
- noitem.nocraft.126.11
- noitem.nouse.126.11
- noitem.nohave.126.11
```

(That's my item ID for Nova Cataclsym's.)

Here's my CustomBlocks.yml

``` YAML
# For more information on how to set up custom blocks
# Go here -> http://dev.bukkit.org/server-mods/noitem/pages/configuring-custom-blocks/

# How to set up a furnace block #
# blockname: 
#     id: 
#     data: 
#     type: furnace
#     itemSlots: 
#     fuelSlots: 
#     resultSlots: 
#     usesFuel: 

# How to set up a workbench block #
#     id: 
#     data: 
#     type: workbench
#     recipeSlots: 
#     resultSlots: 
#     fakeRecipeItems: 

# Here is an example of each #

RMFurnace: 
    id: 126
    data: 4
    type: furnace
    itemSlots: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    fuelSlots: [0]
    resultSlots: [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
    usesFuel: true

BlulectricFurnace: 
    id: 137
    data: 4
    type: furnace
    itemSlots: [0, 1, 2, 3, 4, 5, 6, 7 , 8]
    resultSlots: [10]

ProjectTable: 
    id: 137
    data: 3
    type: workbench
    resultSlots: [9]
    recipeSlots: [0, 1, 2, 3, 4, 5, 6, 7, 8]

AutomaticCraftingTableMkII: 
    id: 194
    data: 1
    type: workbench
    recipeSlots: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    resultSlots: [0]
    fakeRecipeItems: true
```

I have a ton of other tekkit item ID's blocked for a couple groups that I haven't tested yet...  I can't get the debug to work for some reason.

**Comment by just-push-it** [comment]
Yeah, the config system was a bit retarded in 2.0.6, Try out 2.0.7-BETA2 and see if it yields better results :) Also, if you decide to use he beta, make sure to update when the final version is released.

**Comment by bjeardoe** [comment]
Still having issues... could there be a plugin compatability issue? 

``` YAML
---- NoItem Debug Dump File ----
Plugin Version: 2.0.7-SNAPSHOT-204
CraftBukkit Version: 1.2.5-R4.1-MCPC-SNAPSHOT
Minecraft Version: git-Bukkit-jenkins-CraftBukkit-173 (MC: 1.2.5)
Max Players: 25
Online Players: 2
Online Mode: false
Using Vault: true
Date/Time: Oct 10, 2012 - 22:21:50 Central Daylight Time
=================================
Item List Size: 0
Item List Values: 
    EMPTY
=================================
--- Installed Plugins ---
- mod_WirelessRedstoneAddons - ForgeMod
- mod_BuildCraftEnergy - ForgeMod
- mod_RedPowerWiring - ForgeMod
- GroupManager - 2.0 (2.9.4) (Phoenix)
- No_Grief_Ip_Logger - 1.1
- mod_BuildCraftCore - ForgeMod
- mod_ImmibisCore - ForgeMod
- Vault - 1.2.18-b229
- Multiverse-Core - 2.4-b527
- mod_BuildCraftFactory - ForgeMod
- mod_NetherOres - ForgeMod
- mod_EE - ForgeMod
- mod_TubeStuff - ForgeMod
- Permissions - 3.1.6
- mod_CCTurtle - ForgeMod
- milkAdmin - 1.9-07.08
- mod_WirelessRedstoneRedPower - ForgeMod
- mod_IC2NuclearControl - ForgeMod
- mod_ccSensors - ForgeMod
- mod_ImmiChunkLoaders - ForgeMod
- mcMMO - 1.3.09-b945
- mod_CompactSolars - ForgeMod
- mod_WirelessRedstoneCore - ForgeMod
- mod_IC2_ChargingBench - ForgeMod
- mod_IronChest - ForgeMod
- mod_MinecraftForge - ForgeMod
- BoatDrop - 0.4
- WorldEdit - 5.3
- Jobz - 1.2.1.0r0
- Multiverse-Inventories - 2.5-b207
- mod_RedPowerControl - ForgeMod
- NoItem - 2.0.7-SNAPSHOT-204
- PermissionsEx - 1.19.3
- mod_IC2 - ForgeMod
- LogBlock - 1.60
- mod_RedPowerMachine - ForgeMod
- mod_BuildCraftBuilders - ForgeMod
- LWC - 4.3.0 (b736-git-1b1150b1) (August 08, 2012)
- mod_RedPowerLighting - ForgeMod
- WorldGuard - 5.5.2 FOR TEKKIT 3.0.3 [AlienX]
- mod_RedPowerWorld - ForgeMod
- No_Grief Spy - 1.1
- mod_ComputerCraft - ForgeMod
- Lottery - 0.8.1
- mod_BuildCraftTransport - ForgeMod
- mod_NotEnoughItems - ForgeMod
- NGlogger - 1.2
- mod_PowerConverters - ForgeMod
- mod_AdditionalPipes - ForgeMod
- disablecraft - 0.12.2
- ExperienceMod - 2.2.6
- mod_Railcraft - ForgeMod
- mod_IC2AdvancedMachines - ForgeMod
- mod_RedPowerCore - ForgeMod
- mod_RedPowerLogic - ForgeMod
- Modifyworld - 1.19.3
- mod_ModularForceFieldSystem - ForgeMod
- Herochat - 5.6.0
- mod_EnderStorage - ForgeMod
- mod_CodeChickenCore - ForgeMod
- Balkon's WeaponMod - ForgeMod
- Essentials - 2.9.4
- Multiverse-Portals - 2.4-b548
- dynmap - 0.80-1315
- Dynmap-WorldGuard - 0.30
- EssentialsProtect - 2.9.4
- EssentialsSpawn - 2.9.4
- EssentialsGeoIP - 2.9.4
- Dynmap-HeroChat - 0.30
- dynmap-mobs - 0.30
=================================
--- Config Options ---
Notify - MemorySection[path='Notify', root='YamlConfiguration']
Notify.Admins - false
Notify.AdminMessage - &e%n &9tried to &c%t %i &9in world %w @ &a%x,%y,%z
Notify.NoUse - true
Notify.NoUseMessage - &9You are not allowed to use a(n) &4%i&9!
Notify.NoBrew - true
Notify.NoBrewMessage - You are not allowed to brew that potion! &4(%i)
Notify.NoHold - true
Notify.NoHoldMessage - You are not allowed to hold &4%i&9!
Notify.NoWear - true
Notify.NoWearMessage - You are not allowed to wear &4%i&9!
Notify.NoCraft - true
Notify.NoCraftMessage - You are not allowed to craft &4%i&9.
Notify.NoPickup - true
Notify.NoPickupMessage - You are not allowed to pick that up! (%i)
Notify.NoCook - true
Notify.NoCookMessage - You are not allowed to cook &4%i&9.
Notify.NoDrop - true
Notify.NoDropMessage - You are not allowed to drop &4%i.
Notify.NoBreak - true
Notify.NoBreakMessage - You are not allowed to break &4%i.
Notify.NoPlace - true
Notify.NoPlaceMessage - You are not allowed to place &4%i.
Notify.NoDrink - true
Notify.NoDrinkMessage - You are not allowed to drink that!
Notify.NoOpen - true
Notify.NoOpenMessage - You are not allowed to open that!
Debugging - false
PluginChannel - main
CheckForUpdates - true
ConfigurationVersion - 1.1
=================================
--- END DEBUG DUMP ---
```
